server:
  port: 8071
spring:
  profiles:
    active: git
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kal-bishnoi/ukg-config-service.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
    endpoints:
        web:
          exposure:
            include: "*"
    endpoint:
      health:
        probes:
          enabled: true
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
